server {
    listen 80;
    server_name localhost;

    # 1. Serwowanie frontendu w React
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        
        # Magia dla React Routera: jeśli Nginx nie znajdzie pliku, oddaje stronę index.html
        try_files $uri $uri/ /index.html; 
    }

    # 2. Reverse Proxy do backendu w Expressie
    # Złapie wszystko co idzie na http://twojadomena.pl/api/ i wyśle do kontenera z backendem
    location /api/ {
        # 'backend' to nazwa serwisu z docker-compose.yml
        # Zapytanie do /api/users Nginx wyśle jako http://backend:3000/api/users
        proxy_pass http://backend:3000/; 
        
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_cache_bypass $http_upgrade;
    }
}
